apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pets
      service: web
      color: green
  template:
    metadata:
      labels:
        app: pets
        service: web
        color: green
    spec:
      containers:
      - image: fredysa/web:2.1
        name: web
        ports:
        - containerPort: 3000
          protocol: TCP