version: "2.4"
services:
    probe-demo:
        image: fredysa/demo:1.0
        build: .
        healthcheck:
            test: cat /app/healthy
            start_period: 5s
            interval: 3s
            retries: 2