apiVersion: v1
kind: Pod
metadata:
  name: probes-demo
spec:
  containers:
  - name: probes-demo
    image: fredysa/demo:1.0
    livenessProbe:
      exec:
        command:
        - cat
        - /app/healthy
      initialDelaySeconds: 5
      periodSeconds: 5