version: '3.1'

services:

  wordpress:
    image: fredysa/wordpress:1.0
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: Admin
      WORDPRESS_DB_PASSWORD: Pa55w.rd
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: fredysa/wp-db:1.0 
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Pa55w.rd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:


